### ISSUE TITLE
Still functional with current ShopRite site?

### ISSUE THREAD

**Issue by edge360** [primaryobjects/grocery-digital-coupons#3]
Hi, I wanted to see if this script is still functional with the current Shoprite website?

I was having trouble with chromedriver and finally got the script to start by adding the following chromedriver options -
    options.add_argument('headless')
    options.add_argument("--no-sandbox")
    options.add_argument("--remote-debugging-port=9222")

Using:
Google Chrome 97.0.4692.20 beta 
and
ChromeDriver 97.0.4692.20 (6559bb085abcaedffe35d268b3546c43f755151c-refs/branch-heads/4692@{#186})

Working off of a python:3.8.3 docker image.

Finally got the script running, but it crashes at "Waiting for login page." Is there a recommended Chrome/driver version? Or any other configs/args recommended?

Thanks!

Using ./chromedriver
Navigating to home page.
Locating sign-in page.
Waiting for login page.
Message: 
Stacktrace:
#0 0x555865d799f3 <unknown>
#1 0x5558658417d8 <unknown>
#2 0x5558658779d1 <unknown>
#3 0x555865877b91 <unknown>
#4 0x5558658aa6f4 <unknown>
#5 0x55586589526d <unknown>
#6 0x5558658a848b <unknown>
#7 0x555865895133 <unknown>
#8 0x55586586ac2a <unknown>
#9 0x55586586bcf5 <unknown>
#10 0x555865dab2fd <unknown>
#11 0x555865dc183b <unknown>
#12 0x555865dad015 <unknown>
#13 0x555865dc2335 <unknown>
#14 0x555865da0a2f <unknown>
#15 0x555865ddcfa8 <unknown>
#16 0x555865ddd128 <unknown>
#17 0x555865df802d <unknown>
#18 0x7ff3022d6fa3 <unknown>

**Comment by primaryobjects** [comment]
Yes, it should be functional. I'm not sure it will work in headless mode with Selenium though, which is why the option is [commented out](https://github.com/primaryobjects/grocery-digital-coupons/blob/master/grocery_coupons.py#L22).

I would recommend trying without the headless option and allowing the web browser to visibly open and display. You can also watch the progress and web pages load in this manner, to help debug any issue. Thanks.
